paperless:
  image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 2.20.13
  env:
    PAPERLESS_TIME_ZONE: "Europe/London"
    PAPERLESS_OCR_LANGUAGE: "eng"
    PAPERLESS_TIKA_ENABLED: "1"
    PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paperless.tailc14988.ts.net,https://paperless.services.rhoades-brown.local"
    PAPERLESS_URL: "https://paperless.tailc14988.ts.net"
  storage:
    data:
      size: 10Gi
    media:
      size: 10Gi
    export:
      size: 5Gi
    consume:
      size: 5Gi

cnpg:
  instances: 1
  storage:
    size: 8Gi

gotenberg:
  image:
    repository: docker.io/gotenberg/gotenberg
    tag: 8.30.0

ingress:
  nginx:
    enabled: true
    host: paperless.services.rhoades-brown.local
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  tailscale:
    enabled: true
    hostname: paperless

redis:
  architecture: standalone
  auth:
    enabled: false
  image:
    tag: latest
  master:
    persistence:
      enabled: false

tika:
  image:
    tag: latest

