apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  PAPERLESS_REDIS: "redis://{{ .Release.Name }}-redis-master:6379"
  PAPERLESS_DBENGINE: "postgresql"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://{{ .Release.Name }}-gotenberg:3000"
  PAPERLESS_TIKA_ENDPOINT: "http://{{ .Release.Name }}-tika:9998"
  {{- range $key, $val := .Values.paperless.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

