apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/paperless-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: paperless
          image: "{{ .Values.paperless.image.repository }}:{{ .Values.paperless.image.tag }}"
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-paperless
          env:
            - name: PAPERLESS_DBHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-cluster-app
                  key: host
            - name: PAPERLESS_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-cluster-app
                  key: dbname
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-cluster-app
                  key: username
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-cluster-app
                  key: password
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: export
              mountPath: /usr/src/paperless/export
            - name: consume
              mountPath: /usr/src/paperless/consume
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-media
        - name: export
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-export
        - name: consume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-consume

