apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: penpot-cluster
  namespace: penpot
spec:
  instances: 1
  enableSuperuserAccess: true

  storage:
    size: 8Gi

  bootstrap:
    initdb:
      database: penpot
      owner: penpot
