---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: truenas-csp
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: hpe-csi (username is a no-op when using API key)
  password: 3-oAFMqfzLSxaxo76Cc141u5dsp4pC6jUgSUl3AyqrRrjgPEQpiOr8m9R0b5lw8U4B
  backend: truenas.rhoades-brown.local