#cloudflare-secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-admin-secret
spec:
  secretStoreRef:
    name: pulumi-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-admin-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: minio-admin
