apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: obsidian-livesync-tunnel-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
  - name: obsidian-livesync-minio
    kind: Service
    spec:
      fqdn: obsidian.rhoades-brown.co.uk
      protocol: https
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel
