apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "open-notebook.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: pulumi-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: encryptionKey
      remoteRef:
        key: open-notebook.encryptionKey
    - secretKey: surrealPassword
      remoteRef:
        key: open-notebook.surrealPassword
