apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-surrealdb
  labels:
    app.kubernetes.io/name: surrealdb
    {{- include "open-notebook.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.surrealdb.storage.size }}
