apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: argocd
  annotations:
    {{- if .Values.kargo.enabled }}
    kargo.akuity.io/authorized-stage: "{{ include "app-loader.kargoProject" . }}:prod"
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  sources:
    {{- if .Values.chart.repoURL }}
    - repoURL: {{ .Values.chart.repoURL }}
      targetRevision: {{ .Values.chart.version | quote }}
      chart: {{ .Values.chart.name }}
      {{- if .Values.valuesFile }}
      helm:
        valueFiles:
          - $values/{{ .Values.valuesFile }}
      {{- end }}
    {{- else if .Values.helmPath }}
    - repoURL: {{ .Values.gitRepo }}
      targetRevision: {{ .Values.targetRevision }}
      path: {{ .Values.helmPath }}
      {{- if .Values.valuesFile }}
      helm:
        valueFiles:
          - $values/{{ .Values.valuesFile }}
      {{- end }}
    {{- else if .Values.gitSource.repoURL }}
    - repoURL: {{ .Values.gitSource.repoURL }}
      targetRevision: {{ .Values.gitSource.targetRevision }}
      path: {{ .Values.gitSource.path }}
    {{- end }}
    {{- if .Values.valuesFile }}
    - repoURL: {{ .Values.gitRepo }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
    {{- end }}
    {{- if .Values.manifestsPath }}
    - repoURL: {{ .Values.gitRepo }}
      targetRevision: {{ .Values.targetRevision }}
      path: {{ .Values.manifestsPath }}
    {{- end }}
  syncPolicy:
    {{- with .Values.managedNamespaceMetadata }}
    managedNamespaceMetadata:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      {{- range .Values.extraSyncOptions }}
      - {{ . }}
      {{- end }}

