#cloudflare-secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    name: pulumi-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare
