# clustertunnel.yaml
apiVersion: networking.cfargotunnel.com/v1alpha2
kind: ClusterTunnel
metadata:
  name: cluster-tunnel # The ClusterTunnel Custom Resource Name
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  newTunnel:
    name: talos-tunnel # Name of your new tunnel on Cloudflare
  size: 2 # This is the number of replicas for cloudflared
  cloudflare:
    email: mark@rhoades-brown.co.uk # Your email used to login to the Cloudflare Dashboard
    domain: rhoades-brown.co.uk # Domain under which the tunnel runs and adds DNS entries to
    secret: cloudflare-secrets # The secret created before
    accountId: 51f55506e39720085fb492cd2f45a30c
