---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-photos
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /mnt/RustyPool/Photographs
    server: truenas.rhoades-brown.local