image:
  repository: iib0011/omni-tools
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  nginx:
    enabled: true
    host: omni-tools.services.rhoades-brown.local
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tailscale:
    enabled: true
    hostname: omni-tools

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
