apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-apps
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - git:
        repoURL: https://github.com/rhoades-brown/argo-config.git
        revision: {{ .Values.targetRevision }}
        files:
          - path: "configs/*.yaml"
  template:
    metadata:
      name: '{{ "{{.name}}" }}-loader'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        namespace: '{{ "{{.namespace}}" }}'
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/rhoades-brown/argo-config.git
          targetRevision: {{ .Values.targetRevision }}
          path: app-loader
          helm:
            valueFiles:
              - $values/configs/{{ "{{.name}}" }}.yaml
        - repoURL: https://github.com/rhoades-brown/argo-config.git
          targetRevision: {{ .Values.targetRevision }}
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

