apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.3
    helm:
      valuesObject:
        dashboard:
          enabled: true
          ingress:
            enabled: true
            ingressclassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            hosts:
              - argo-rollouts.services.rhoades-brown.local
            tls:
              - hosts:
                  - argo-rollouts.services.rhoades-brown.local
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/preserveUnknownFields
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
