---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://charts.jetstack.io'
      targetRevision: v1.19.2
      chart: cert-manager
      helm:
        valueFiles:
          - $values/valuesfiles/cert-manager.yaml

    - repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
