apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    name: ''
    namespace:  kube-system
    server: 'https://kubernetes.default.svc'
  sources:
  - path: ''
    repoURL: https://helm.cilium.io/
    targetRevision: 1.18.3
    chart: cilium
    helm:
      valuesObject:
        ipam:
            mode: kubernetes
        kubeProxyReplacement: true
        securityContext:
          capabilities:
            ciliumAgent: 
             - CHOWN
             - KILL
             - NET_ADMIN
             - NET_RAW
             - IPC_LOCK
             - SYS_ADMIN
             - SYS_RESOURCE
             - DAC_OVERRIDE
             - FOWNER
             - SETGID
             - SETUID
            cleanCiliumState: 
             - NET_ADMIN
             - SYS_ADMIN
             - SYS_RESOURCE
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        k8sServiceHost: localhost
        k8sServicePort: 7445
        gatewayAPI:
          enabled: true
          enableAlpn: true
          enableAppProtocol: true


  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


