apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: cloudflare-operator-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/adyanth/cloudflare-operator.git'
    path: config/default
    targetRevision: main
    kustomize:
      namespace: cloudflare-operator-system
  sources: []
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


