apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: client/config/crd
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v8.2.0
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
