apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: client/config/crd
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v8.2.0
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
