apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: grafana-k8s-monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.3.1
    chart: k8s-monitoring
    helm:
      valuesObject:
        extraObjects:
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: access-policy-token
            spec:
              secretStoreRef:
                name: pulumi-secret-store
                kind: ClusterSecretStore
              target:
                name: access-policy-token
                creationPolicy: Owner
              dataFrom:
                - extract:
                    key: k8s-monitoring

        cluster:
          name: talos
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-05-gb-south-0.grafana.net./api/prom/push
            auth:
              type: basic
            secret:
              create: false
              name: access-policy-token
          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-008.grafana.net./loki/api/v1/push
            auth:
              type: basic
            secret:
              create: false
              name: access-policy-token
          - name: grafana-cloud-otlp-endpoint
            type: otlp
            url: https://otlp-gateway-prod-gb-south-0.grafana.net./otlp
            protocol: http
            auth:
              type: basic
            secret:
              create: false
              name: access-policy-token
            metrics:
              enabled: true
            logs:
              enabled: true
            traces:
              enabled: true
        clusterMetrics:
          enabled: true
          kepler:
            enabled: true
        clusterEvents:
          enabled: true
        podLogs:
          enabled: true
        applicationObservability:
          enabled: true
          receivers:
            otlp:
              grpc:
                enabled: true
                port: 4317
              http:
                enabled: true
                port: 4318
            zipkin:
              enabled: true
              port: 9411
        alloy-metrics:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: access-policy-token
                    key: password
              - name: CLUSTER_NAME
                value: talos
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-006.grafana.net
            auth:
              type: basic
            secret:
              create: false
              name: access-policy-token
        alloy-singleton:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: access-policy-token
                    key: password
              - name: CLUSTER_NAME
                value: talos
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-006.grafana.net
            auth:
              type: basic
            secret:
              create: false
              name: access-policy-token
        alloy-logs:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: access-policy-token
                    key: password
              - name: CLUSTER_NAME
                value: talos
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-006.grafana.net
            auth:
              type: basic
            secret:
              create: false
              name: access-policy-token
        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP
              - name: otlp-http
                port: 4318
                targetPort: 4318
                protocol: TCP
              - name: zipkin
                port: 9411
                targetPort: 9411
                protocol: TCP
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: access-policy-token
                    key: password
              - name: CLUSTER_NAME
                value: talos
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-006.grafana.net
            auth:
              type: basic
            secret:
              create: false
              name: access-policy-token


  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
