---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: immich
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://immich-app.github.io/immich-charts"
      targetRevision: 0.9.3
      chart: immich
      helm:
        valuesObject:
          image:
            tag: v1.142.0

          immich:
            metrics:
              enabled: true
            persistence:
              # Main data store for all photos shared between different components.
              library:
                # Automatically creating the library volume is not supported by this chart
                # You have to specify an existing PVC to use
                existingClaim: nfs-photos

          server:
            enabled: true
            env:
            - name:  REDIS_HOSTNAME
              value: immich-redis-master
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-superuser
                  key: host
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-app
                  key: dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-superuser
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-superuser
                  key: password
            ingress:
              main:
                enabled: true
                className: nginx
                annotations:
                  # proxy-body-size is set to 0 to remove the body limit on file uploads
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                hosts:
                  - host: immich.services.rhoades-brown.local
                    paths:
                      - path: "/"
                tls: []

          redis:
            enabled: true
    - path: manifests/immich
      repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
