---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: immich
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://immich-app.github.io/immich-charts"
      targetRevision: 0.4.0
      chart: immich
      helm:
        values: |
          image:
            tag: v1.100.0

          immich:
            persistence:
              # Main data store for all photos shared between different components.
              library:
                # Automatically creating the library volume is not supported by this chart
                # You have to specify an existing PVC to use
                existingClaim: nfs-photos

          server:
            enabled: true
            image:
              repository: ghcr.io/immich-app/immich-server
              pullPolicy: IfNotPresent
            
            ingress:
              main:
                enabled: true
                annotations:
                  # proxy-body-size is set to 0 to remove the body limit on file uploads
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                hosts:
                  - host: immich.services.rhoades-brown.local
                    paths:
                      - path: "/"
                tls: []
          postgresql:
            enabled: true
          redis:
            enabled: true
    - path: other/immich
      repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
