apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rhoades-brown/kargo-config.git
    targetRevision: main
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
