apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  sources:
    - repoURL: ghcr.io/akuity/kargo-charts
      chart: kargo
      targetRevision: v1.9.5
      helm:
        valueFiles:
          - $values/kargo/values.yaml
    - repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
      ref: values
      path: manifests/kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true