---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: kube-prometheus-stack
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 61.1.1
    chart: kube-prometheus-stack
    helm:
        values: |
          alertmanager:
            ingress:
              enabled: true
              hosts:
              - alertmanager.services.rhoades-brown.local
              annotations:
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          
          grafana:
            ingress:
              enabled: true
              hosts:
              - grafana.services.rhoades-brown.local
              annotations:
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          prometheus:
            ingress:
              enabled: true
              hosts:
              - prometheus.services.rhoades-brown.local
              annotations:
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  sources: []
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
