---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
      kind: CustomResourceDefinition
  destination:
    namespace: metallb-system
    server: "https://kubernetes.default.svc"
  sources:
  - repoURL: "https://metallb.github.io/metallb"
    targetRevision: 0.15.2
    chart: metallb
    helm:
  - path: helm/metallb-config
    repoURL: 'https://github.com/rhoades-brown/argo-config.git'
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valuesObject:
        poolName:  default-pool
        ipAddressRange: 
          - '192.168.1.69/29'

  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
