---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: obsidian-livesync
    server: "https://kubernetes.default.svc"
  sources:
  - repoURL: https://charts.min.io
    targetRevision: 5.4.0
    chart: minio
    helm:
        valuesObject:
          existingSecret: minio-admin-secret
          replicas: 3
          resources:
            requests:
              memory: 1Gi
          ingress:
            enabled: true
            className: nginx
            hosts:
              - obsidian.services.rhoades-brown.local
            path: /
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          consoleIngress:
            enabled: true
            className: nginx
            hosts:
              - obsidian-console.services.rhoades-brown.local

          buckets:
            - name: mark
              policy: none
              purge: false
          users:
            ## Username, password and policy to be assigned to the user
            ## Default policies are [readonly|readwrite|writeonly|consoleAdmin|diagnostics]
            ## Add new policies as explained here https://min.io/docs/minio/kubernetes/upstream/administration/identity-access-management.html#access-management
            ## NOTE: this will fail if LDAP is enabled in your MinIO deployment
            ## make sure to disable this if you are using LDAP.
            - accessKey: console
              secretKey: console123
              policy: consoleAdmin
            # Or you can refer to specific secret
            - accessKey: mark
              existingSecret: obsidian-mark-user
              existingSecretKey: password
              policy: readwrite
  - repoURL: https://github.com/rhoades-brown/argo-config
    targetRevision: main
    path: manifests/obsidian-livesync
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
