apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ollama
    server: 'https://kubernetes.default.svc'
  source:
    repoURL:  https://otwld.github.io/ollama-helm/
    targetRevision: 0.57.0
    chart: ollama
    helm:
      values: |
        ollama:
          models:
            - llama3.1
            - starcoder2:3b
        persistentVolume:
          enabled: true
        ingress:
          enabled: true
          hosts:
            - host: ollama.services.rhoades-brown.local
              paths:
                - path: /
                  pathType: Prefix
        resources:
          requests:
            memory: 6Gi
          limits: 
             memory: 12Gi

  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


     