apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: open-webui
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://helm.openwebui.com/
    targetRevision: 6.16.0
    chart: open-webui
    helm:
      valuesObject:
        oolama:
            persistentVolume:
              enabled: true
        ingress:
          enabled: true
          class: "nginx"
          annotations: 
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
          host: "open-webui.services.rhoades-brown.local" # update to your real domain

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
