apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  annotations:
    kargo.akuity.io/authorized-stage: kargo-open-webui:prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: open-webui
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://helm.openwebui.com/
      targetRevision: 12.8.1
      chart: open-webui
      helm:
        valueFiles:
          - $values/valuesfiles/open-webui.yaml

    - repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
