apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: open-webui
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://helm.openwebui.com/
    targetRevision: 6.16.0
    chart: open-webui
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
