---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openspeedtest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: openspeedtest
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://openspeedtest.github.io/Helm-chart'
      targetRevision: 0.1.2
      chart: openspeedtest
      helm:
        valueFiles:
          - $values/valuesfiles/openspeedtest.yaml

    - repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
