---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: stirlingpdf
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://stirling-tools.github.io/Stirling-PDF-chart"
      targetRevision: 2.2.0
      chart: stirling-pdf-chart
      helm:
        valuesObject:
          serviceMonitor:
            enabled: true
          persistence:
            enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              # proxy-body-size is set to 0 to remove the body limit on file uploads
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            hosts:
              - name: pdf.services.rhoades-brown.local
                tls: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
