---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: stirlingpdf
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://stirling-tools.github.io/Stirling-PDF-chart"
      targetRevision: 3.1.0
      chart: stirling-pdf-chart
      helm:
        valueFiles:
          - $values/valuesfiles/pdf.yaml

    - repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
