---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: sealed-secrets-controller
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 2.17.0
    chart: sealed-secrets
    helm:
      valuesObject:
        secretName: sealed-secret-key
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
