apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "tailscale"
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.94.2
      chart: tailscale-operator
      helm:
        valuesObject:
#          oauth:
#            clientId: "set-me"
#            clientSecret: "set-me"
    - path: manifests/tailscale
      repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: {{ .Values.targetRevision }}
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
