apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: transmission
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.truecharts.org/'
    targetRevision: 20.5.2
    chart: transmission
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
