---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: whoami
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/whoami
    repoURL: 'https://github.com/rhoades-brown/argo-config.git'
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: nginx
          annotations: 
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
            - host: whoami.services.rhoades-brown.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
              - whoami.services.rhoades-brown.local
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
