apiVersion: gateway.nginx.org/v1alpha1
kind: NginxGateway
metadata:
  name: {{ include "nginx-gateway.config-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.nginxGateway.config | nindent 2 }}
