# operator-oauth

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  secretStoreRef:
    name: pulumi-secret-store
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: tailscale
