---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-videos
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /mnt/RustyPool/Videos
    server: truenas.rhoades-brown.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-videos
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
