apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0
  instances: 1
  enableSuperuserAccess: true
  superuserSecret:
    name: immich-superuser

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  storage:
    size: 12Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
spec:
  name: app
  owner: app
  cluster:
    name: immich-cluster
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
      version: 0.3.0
    - name: earthdistance
      ensure: present
