apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: immich-tunnel-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
  - name: immich-server
    kind: Service
    spec:
      fqdn: immich.rhoades-brown.co.uk
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel
