apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: colour
spec:
  metrics:
    - name: colour 
      successCondition: result == '{{ .Values.name }}'
      provider:
        web:
          url: "https://whoami.services.rhoades-brown.local/api"
          insecure: true
          jsonPath: "{$.name}"
