apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: colour
spec:
  args:
  - name: whoami-canary
    interval: 1s
    failureLimit: 3
    successCondition: result == '{{ .Values.name }}'
  metrics:
    provider:
      web:
        url: "https://whoami.services.rhoades-brown.local/api"
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.name}"
