apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: whoami-canary
  metrics:
    provider:
      web:
        url: "https://whoami.services.rhoades-brown.local/api"
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.name}"
