apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: colour
spec:
  metrics:
    - name: colour 
      successCondition: result == '{{ .Values.name }}'
      provider:
        web:
          url: "http://whoami.services.rhoades-brown.local/api"
          timeoutSeconds: 20 # defaults to 10 seconds
          jsonPath: "{$.name}"
