name: cloudnative-postgres-operator
namespace: cnpg-system

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-cloudnative-postgres-operator-prod.01kngkq6cv7cbd3am6yye4xcf0.c1c0dc0

chart:
  repoURL: https://cloudnative-pg.github.io/charts
  name: cloudnative-pg
  version: 0.28.0

extraSyncOptions:
  - ServerSideApply=true

kargo:
  enabled: true
  project: kargo-cloudnative-postgres-operator
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://cloudnative-pg.github.io/charts
      name: cloudnative-pg
      semverConstraint: ">=0.27.0"
  stage:
    imageUpdates: []

