name: omni-tools
namespace: omni-tools

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-omni-tools-prod.01knx4g0ms2xwwcqqd6jjwn137.37df074

helmPath: helm/omni-tools

kargo:
  enabled: true
  project: kargo-omni-tools
  autoPromotionEnabled: true
  warehouse:
    interval: 1h0m0s
    images:
      - repoURL: docker.io/iib0011/omni-tools
        imageSelectionStrategy: Digest
        constraint: latest
    chart:
      repoURL: ""
      semverConstraint: ""
  stage:
    imageUpdates:
      - key: image.tag
        image: docker.io/iib0011/omni-tools
        file: helm/omni-tools/values.yaml
