name: open-webui
namespace: open-webui
chartRepoURL: https://helm.openwebui.com/
chartName: open-webui
chartVersion: "12.8.1"
valuesFile: valuesfiles/open-webui.yaml
kargoAuthorizedStage: "kargo-open-webui:prod"

