name: open-webui
namespace: open-webui

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-open-webui-prod.01knb8jyehxr8ja03ve7430r4v.c42d40c

chart:
  repoURL: https://helm.openwebui.com/
  name: open-webui
  version: 13.0.1

valuesFile: valuesfiles/open-webui.yaml

kargo:
  enabled: true
  project: kargo-open-webui
  autoPromotionEnabled: true
  warehouse:
    interval: 1h0m0s
    images:
      - repoURL: ghcr.io/open-webui/open-webui
        tagSelectionStrategy: SemVer
      - repoURL: docker.io/ollama/ollama
        tagSelectionStrategy: SemVer
        allowTags: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    chart:
      repoURL: https://helm.openwebui.com/
      name: open-webui
      semverConstraint: ">=12.0.0"
  stage:
    imageUpdates:
      - key: ollama.image.tag
        image: docker.io/ollama/ollama
        file: valuesfiles/open-webui.yaml

