name: stirling-pdf
namespace: stirlingpdf

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: main

chart:
  repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
  name: stirling-pdf-chart
  version: 3.1.0

valuesFile: valuesfiles/pdf.yaml

kargo:
  enabled: true
  project: kargo-stirling-pdf
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
      name: stirling-pdf-chart
      semverConstraint: ">=3.0.0"
  stage:
    imageUpdates: []

