---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.poolName }}
  namespace: metallb-system
  labels:
    {{- include "metalb-config.labels" . | nindent 4 }}
spec:
  addresses:
    {{- range .Values.ipAddressRange }}
    - {{ . }}
    {{- end }}