---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: truenas-csp
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://democratic-csi.github.io/charts/'
    targetRevision: 0.14.5
    chart: democratic-csi
    helm:
      valueFiles:
        - ../valuesfiles/democratic-csi.yaml
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
