---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://metallb.github.io/metallb'
      targetRevision: 0.13.12
      chart: metallb
      helm:
 #     parameters:
 #       - name: installCRDs
 #         value: 'true'
    - path: helm/metallb-config
      repoURL: 'https://github.com/rhoades-brown/argo-config.git'
      targetRevision: initial
      helm:
      parameters:
         - name: ipAddressRange[0]
           value: '192.168.1.70'
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
