apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
spec:
  secretStoreRef:
    name: pulumi-secret-store
    kind: ClusterSecretStore
  target:
    name: democratic-csi-driver-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: democratic-csi
