---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-open-webui
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: open-webui
  namespace: kargo-open-webui
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/open-webui/open-webui
        tagSelectionStrategy: SemVer
    - image:
        repoURL: docker.io/ollama/ollama
        tagSelectionStrategy: SemVer
        allowTags: ^[0-9]+\.[0-9]+\.[0-9]+$
    - git:
        repoURL: https://github.com/rhoades-brown/argo-config.git
        branch: main
        includePaths:
          - valuesfiles/open-webui.yaml
          - configs/open-webui.yaml
    - chart:
        repoURL: https://helm.openwebui.com/
        name: open-webui
        semverConstraint: ">=12.0.0"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-open-webui
spec:
  autoPromotionEnabled: true
  requestedFreight:
    - origin:
        kind: Warehouse
        name: open-webui
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/rhoades-brown/argo-config.git
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
        - uses: yaml-update
          as: update-ollama
          config:
            path: ./src/valuesfiles/open-webui.yaml
            updates:
              - key: ollama.image.tag
                value: ${{ imageFrom("docker.io/ollama/ollama").Tag }}
        - uses: yaml-update
          as: update-chart
          config:
            path: ./src/configs/open-webui.yaml
            updates:
              - key: chartVersion
                value: ${{ chartFrom("https://helm.openwebui.com/", "open-webui").Version }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: |
              ${{ outputs['update-ollama'].commitMessage }}
              ${{ outputs['update-chart'].commitMessage }}
        - uses: git-push
          config:
            path: ./src
        - uses: argocd-update
          config:
            apps:
              - name: open-webui
                namespace: argocd
                sources:
                  - repoURL: https://helm.openwebui.com/
                    chart: open-webui
                    desiredRevision: ${{ chartFrom("https://helm.openwebui.com/", "open-webui").Version }}
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}