---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-open-webui
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: open-webui
  namespace: kargo-open-webui
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/open-webui/open-webui
        tagSelectionStrategy: SemVer
    - image:
        repoURL: docker.io/ollama/ollama
        tagSelectionStrategy: SemVer
    - git:
        repoURL: https://github.com/rhoades-brown/argo-config.git
        branch: main
        includePaths:
          - valuesfiles/open-webui.yaml
    - chart:
        repoURL: https://helm.openwebui.com/
        name: open-webui
        semverConstraint: ">=12.0.0"